#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World'.
#

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# create directory for actual web content
# sudo mkdir -p /var/www/html
# sudo touch /var/www/html/index.html

# assign ownership to the account that
# we are currently signed in on
sudo chown -R "$USER:$USER" /var/www/

# confirm permission of webroot
# sudo chmod -R 755 /var/www

#return a page that contains the string Hello World!
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without using systemctl
sudo service nginx restart
